// src/components/SearchInput.tsx
import { useState, useEffect } from 'react';

const SearchInput = ({ value, onChange, placeholder, isActive }: any) => {
  const [localValue, setLocalValue] = useState(value);

  useEffect(() => {
    setLocalValue(value);
  }, [value]);

  return (
    <textarea
      value={localValue}
      onChange={(e) => {
        const val = e.target.value;
        setLocalValue(val);
        onChange(val);
      }}
      placeholder={placeholder}
      className="w-full bg-transparent border-none outline-none text-lg resize-none min-h-[100px] placeholder:text-white/30"
    />
  );
};

export default SearchInput;

// RefactorVue/src/components/SearchInput.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

const props = defineProps<{
  modelValue: string;
  placeholder?: string;
}>();

const emit = defineEmits<{
  'update:modelValue': [value: string];
}>();

const localValue = ref(props.modelValue);

watch(() => props.modelValue, (v) => { localValue.value = v; });

function onInput(e: Event) {
  const val = (e.target as HTMLTextAreaElement).value;
  localValue.value = val;
  emit('update:modelValue', val);
}
</script>

<template>
  <textarea
    :value="localValue"
    @input="onInput"
    :placeholder="placeholder"
    class="w-full bg-transparent border-none outline-none text-lg resize-none min-h-[100px] placeholder:text-white/30"
  />
</template>
